#!/bin/bash

# This script is responsible for:
# - Mounting all system relevant directories
#     - /proc:  mount -t proc proc /proc
#     - /sys:   mount -t sysfs sysfs /sys
# - To evaluate: mounting the overlay filesystem (see rootfs-builder-3/files_debootstrap/sbin/overlay-init)
# - Setting up the network, based on the kernel args

# The reason this is implemented in a shell script is because it is more leightweight than a (go) executable.

VERSION="v1.0.2"

# Function to log messages with the system uptime from /proc/stat
log() {
  message="$1"

  # Get the boot time (seconds since epoch) from /proc/stat
  boot_time_epoch=$(grep -Po '^btime \K\d+' /proc/stat)

  current_seconds=$(date +%s)
  current_nanoseconds=$(date +%N)

  # Remove leading zeros to prevent octal interpretation
  current_nanoseconds=$((10#$current_nanoseconds))

  # Calculate the integer part of time since boot
  int_time_since_boot=$((current_seconds - boot_time_epoch))

  # Calculate the fractional part (in seconds) - convert nanoseconds to seconds
  frac_time_since_boot=$(printf "%.6f" "$((current_nanoseconds))e-9")

  time_since_boot="${int_time_since_boot}${frac_time_since_boot:1}"
  display_time=$(printf "[%12s]" "$time_since_boot")

  echo "$display_time $message"
}

# Function to log messages for situations where /proc/stat is not available
log_blank() {
  message=$1
  echo "               $message"
}

# Function to parse kernel command line argument and export it as an environment variable
parse_and_export_env() {
    local arg_name="$1"
    local env_name="$2"

    # Extract the value of the kernel command line argument
    local arg_value=$(cat /proc/cmdline | tr ' ' '\n' | grep "^${arg_name}=" | cut -d'=' -f2)

    # Check if the argument was found and export it as an environment variable
    if [ ! -z "$arg_value" ]; then
        export "$env_name=$arg_value"
        log "$env_name = $arg_value"
    fi
}

# ----- Show init system banner

log_blank "apollo init system - $VERSION"

# ----- Mounting system relevant directories

if [ ! -d "/proc" ]; then
  # Cannot use 'log' here because /proc is not mounted yet
  log_blank "cannot mount proc - /proc does not exist"
  exit 1
fi
/bin/mount -t proc proc /proc
log "mounted proc to /proc"

if [ ! -d "/sys" ]; then
  log "cannot mount sysfs - /sys does not exist"
  exit 1
fi
/bin/mount -t sysfs sysfs /sys
log "mounted sysfs to /sys"

# ----- Mounting the code filesystem

if [ ! -d "/workspace" ]; then
  log "cannot mount codefs - /workspace does not exist"
  exit 1
fi

if [ ! -b "/dev/vdb" ]; then
  log "cannot mount codefs - target drive /dev/vdb does not exist"
  exit 1
fi

/bin/mount /dev/vdb /workspace
log "mounted codefs to /workspace"

# ----- Setting up the network

# Extract the 'ip' argument from the kernel command line
ip_arg=$(cat /proc/cmdline | tr ' ' '\n' | grep '^ip=' | cut -d'=' -f2)

# Check if the ip argument was found
if [ -z "$ip_arg" ]; then
    log "The 'ip' argument was not found in the kernel command line."
    exit 1
fi

# Function to extract a component from the ip argument
extract_component() {
    echo "$ip_arg" | cut -d':' -f"$1"
}

client_ip=$(extract_component 1)
gateway_ip=$(extract_component 3)
netmask=$(extract_component 4)
device=$(extract_component 6)

# Check if the network interface exists
if ! ip link show $device > /dev/null 2>&1; then
    log "network interface $device not found"
    exit 1
fi

# Configure the IP address and netmask
if ! ip addr add $client_ip/$netmask dev $device; then
    log "failed to configure IP address"
    exit 1
fi

# Bring the interface up
if ! ip link set $device up; then
    log "failed to bring up the interface"
    exit 1
fi

# Configure the default gateway
if ! ip route add default via $gateway_ip dev $device; then
    log "failed to configure default gateway"
    exit 1
fi

log "network has been set up with ip $client_ip"

# ----- Set the environment variables parsed from the kernel command line

log "exporting env variables for agent"

parse_and_export_env "wkr-uuid" "APOLLO_WORKER_UUID"
parse_and_export_env "fn-ident" "APOLLO_FUNCTION_IDENTIFIER"
parse_and_export_env "rn-uuid" "APOLLO_RUNNER_UUID"
parse_and_export_env "rt-hdlr" "APOLLO_RUNTIME_HANDLER"
parse_and_export_env "rt-bin-path" "APOLLO_RUNTIME_BINARY_PATH"
parse_and_export_env "rt-bin-args" "APOLLO_RUNTIME_BINARY_ARGS"

parse_and_export_env "api-port" "APOLLO_API_PORT"
parse_and_export_env "msg-srvs" "APOLLO_MESSAGING_BOOTSTRAP_SERVERS"

parse_and_export_env "log-lvl" "APOLLO_LOG_LEVEL"

# ----- Invoke the agent and porceed with the boot process

log "done - run agent"
exec /usr/bin/agent $@