FROM debian:bullseye-slim

WORKDIR /tmp

RUN apt update && apt install --no-install-recommends -y \
  tini \
  systemd-sysv \
  iputils-ping \
  iproute2 \
  udev

COPY ./agent /usr/bin/agent
RUN chmod +x /usr/bin/agent

ENTRYPOINT [ "tail", "-f", "/dev/null" ]