FROM debian:bullseye-slim

WORKDIR /tmp

RUN apt update && apt install --no-install-recommends -y \
  tini \
  systemd-sysv \
  iputils-ping \
  iproute2 \
  udev

ENTRYPOINT [ "tail", "-f", "/dev/null" ]