// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: apollo/proto/messages/v1/messages.proto

package messagespb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FunctionInitializationMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FunctionUuid string `protobuf:"bytes,1,opt,name=function_uuid,json=functionUuid,proto3" json:"function_uuid,omitempty"`
	WorkerUuid   string `protobuf:"bytes,2,opt,name=worker_uuid,json=workerUuid,proto3" json:"worker_uuid,omitempty"`
	Reason       string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Success      bool   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *FunctionInitializationMessage) Reset() {
	*x = FunctionInitializationMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apollo_proto_messages_v1_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FunctionInitializationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionInitializationMessage) ProtoMessage() {}

func (x *FunctionInitializationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_proto_messages_v1_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionInitializationMessage.ProtoReflect.Descriptor instead.
func (*FunctionInitializationMessage) Descriptor() ([]byte, []int) {
	return file_apollo_proto_messages_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *FunctionInitializationMessage) GetFunctionUuid() string {
	if x != nil {
		return x.FunctionUuid
	}
	return ""
}

func (x *FunctionInitializationMessage) GetWorkerUuid() string {
	if x != nil {
		return x.WorkerUuid
	}
	return ""
}

func (x *FunctionInitializationMessage) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *FunctionInitializationMessage) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RunnerAgentReadyMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FunctionUuid string `protobuf:"bytes,1,opt,name=function_uuid,json=functionUuid,proto3" json:"function_uuid,omitempty"`
	RunnerUuid   string `protobuf:"bytes,2,opt,name=runner_uuid,json=runnerUuid,proto3" json:"runner_uuid,omitempty"`
	Reason       string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Success      bool   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *RunnerAgentReadyMessage) Reset() {
	*x = RunnerAgentReadyMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apollo_proto_messages_v1_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunnerAgentReadyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunnerAgentReadyMessage) ProtoMessage() {}

func (x *RunnerAgentReadyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_proto_messages_v1_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunnerAgentReadyMessage.ProtoReflect.Descriptor instead.
func (*RunnerAgentReadyMessage) Descriptor() ([]byte, []int) {
	return file_apollo_proto_messages_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *RunnerAgentReadyMessage) GetFunctionUuid() string {
	if x != nil {
		return x.FunctionUuid
	}
	return ""
}

func (x *RunnerAgentReadyMessage) GetRunnerUuid() string {
	if x != nil {
		return x.RunnerUuid
	}
	return ""
}

func (x *RunnerAgentReadyMessage) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RunnerAgentReadyMessage) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_apollo_proto_messages_v1_messages_proto protoreflect.FileDescriptor

var file_apollo_proto_messages_v1_messages_proto_rawDesc = []byte{
	0x0a, 0x27, 0x61, 0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x61, 0x70, 0x6f, 0x6c, 0x6c,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x2e, 0x76, 0x31, 0x22, 0x97, 0x01, 0x0a, 0x1d, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x75,
	0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x75, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x77, 0x6f,
	0x72, 0x6b, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x91, 0x01,
	0x0a, 0x17, 0x52, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x61,
	0x64, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x75, 0x6e,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x75, 0x69, 0x64, 0x12, 0x1f,
	0x0a, 0x0b, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x42, 0x42, 0x5a, 0x40, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x64, 0x65, 0x6e, 0x6e, 0x69, 0x73, 0x68, 0x69, 0x6c, 0x67, 0x65, 0x72, 0x74, 0x2f, 0x61, 0x70,
	0x6f, 0x6c, 0x6c, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apollo_proto_messages_v1_messages_proto_rawDescOnce sync.Once
	file_apollo_proto_messages_v1_messages_proto_rawDescData = file_apollo_proto_messages_v1_messages_proto_rawDesc
)

func file_apollo_proto_messages_v1_messages_proto_rawDescGZIP() []byte {
	file_apollo_proto_messages_v1_messages_proto_rawDescOnce.Do(func() {
		file_apollo_proto_messages_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_apollo_proto_messages_v1_messages_proto_rawDescData)
	})
	return file_apollo_proto_messages_v1_messages_proto_rawDescData
}

var file_apollo_proto_messages_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_apollo_proto_messages_v1_messages_proto_goTypes = []interface{}{
	(*FunctionInitializationMessage)(nil), // 0: apollo.proto.messages.v1.FunctionInitializationMessage
	(*RunnerAgentReadyMessage)(nil),       // 1: apollo.proto.messages.v1.RunnerAgentReadyMessage
}
var file_apollo_proto_messages_v1_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apollo_proto_messages_v1_messages_proto_init() }
func file_apollo_proto_messages_v1_messages_proto_init() {
	if File_apollo_proto_messages_v1_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apollo_proto_messages_v1_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FunctionInitializationMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apollo_proto_messages_v1_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunnerAgentReadyMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apollo_proto_messages_v1_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apollo_proto_messages_v1_messages_proto_goTypes,
		DependencyIndexes: file_apollo_proto_messages_v1_messages_proto_depIdxs,
		MessageInfos:      file_apollo_proto_messages_v1_messages_proto_msgTypes,
	}.Build()
	File_apollo_proto_messages_v1_messages_proto = out.File
	file_apollo_proto_messages_v1_messages_proto_rawDesc = nil
	file_apollo_proto_messages_v1_messages_proto_goTypes = nil
	file_apollo_proto_messages_v1_messages_proto_depIdxs = nil
}
