// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: apollo/proto/messages/v1/messages.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FunctionInitialized struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FunctionUuid string `protobuf:"bytes,1,opt,name=function_uuid,json=functionUuid,proto3" json:"function_uuid,omitempty"`
	WorkerUuid   string `protobuf:"bytes,2,opt,name=worker_uuid,json=workerUuid,proto3" json:"worker_uuid,omitempty"`
}

func (x *FunctionInitialized) Reset() {
	*x = FunctionInitialized{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apollo_proto_messages_v1_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FunctionInitialized) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionInitialized) ProtoMessage() {}

func (x *FunctionInitialized) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_proto_messages_v1_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionInitialized.ProtoReflect.Descriptor instead.
func (*FunctionInitialized) Descriptor() ([]byte, []int) {
	return file_apollo_proto_messages_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *FunctionInitialized) GetFunctionUuid() string {
	if x != nil {
		return x.FunctionUuid
	}
	return ""
}

func (x *FunctionInitialized) GetWorkerUuid() string {
	if x != nil {
		return x.WorkerUuid
	}
	return ""
}

type FunctionInitializationFailed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FunctionUuid string `protobuf:"bytes,1,opt,name=function_uuid,json=functionUuid,proto3" json:"function_uuid,omitempty"`
	WorkerUuid   string `protobuf:"bytes,2,opt,name=worker_uuid,json=workerUuid,proto3" json:"worker_uuid,omitempty"`
	Reason       string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *FunctionInitializationFailed) Reset() {
	*x = FunctionInitializationFailed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apollo_proto_messages_v1_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FunctionInitializationFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionInitializationFailed) ProtoMessage() {}

func (x *FunctionInitializationFailed) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_proto_messages_v1_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionInitializationFailed.ProtoReflect.Descriptor instead.
func (*FunctionInitializationFailed) Descriptor() ([]byte, []int) {
	return file_apollo_proto_messages_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *FunctionInitializationFailed) GetFunctionUuid() string {
	if x != nil {
		return x.FunctionUuid
	}
	return ""
}

func (x *FunctionInitializationFailed) GetWorkerUuid() string {
	if x != nil {
		return x.WorkerUuid
	}
	return ""
}

func (x *FunctionInitializationFailed) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_apollo_proto_messages_v1_messages_proto protoreflect.FileDescriptor

var file_apollo_proto_messages_v1_messages_proto_rawDesc = []byte{
	0x0a, 0x27, 0x61, 0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x61, 0x70, 0x6f, 0x6c, 0x6c,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x2e, 0x76, 0x31, 0x22, 0x5b, 0x0a, 0x13, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x75,
	0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x75, 0x69, 0x64, 0x12,
	0x1f, 0x0a, 0x0b, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64,
	0x22, 0x7c, 0x0a, 0x1c, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x69, 0x74,
	0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64,
	0x12, 0x23, 0x0a, 0x0d, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x75, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x55, 0x75, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x5f,
	0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x77, 0x6f, 0x72, 0x6b,
	0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x42, 0x40,
	0x5a, 0x3e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65, 0x6e,
	0x6e, 0x69, 0x73, 0x68, 0x69, 0x6c, 0x67, 0x65, 0x72, 0x74, 0x2f, 0x61, 0x70, 0x6f, 0x6c, 0x6c,
	0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apollo_proto_messages_v1_messages_proto_rawDescOnce sync.Once
	file_apollo_proto_messages_v1_messages_proto_rawDescData = file_apollo_proto_messages_v1_messages_proto_rawDesc
)

func file_apollo_proto_messages_v1_messages_proto_rawDescGZIP() []byte {
	file_apollo_proto_messages_v1_messages_proto_rawDescOnce.Do(func() {
		file_apollo_proto_messages_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_apollo_proto_messages_v1_messages_proto_rawDescData)
	})
	return file_apollo_proto_messages_v1_messages_proto_rawDescData
}

var file_apollo_proto_messages_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_apollo_proto_messages_v1_messages_proto_goTypes = []interface{}{
	(*FunctionInitialized)(nil),          // 0: apollo.proto.messages.v1.FunctionInitialized
	(*FunctionInitializationFailed)(nil), // 1: apollo.proto.messages.v1.FunctionInitializationFailed
}
var file_apollo_proto_messages_v1_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apollo_proto_messages_v1_messages_proto_init() }
func file_apollo_proto_messages_v1_messages_proto_init() {
	if File_apollo_proto_messages_v1_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apollo_proto_messages_v1_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FunctionInitialized); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apollo_proto_messages_v1_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FunctionInitializationFailed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apollo_proto_messages_v1_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apollo_proto_messages_v1_messages_proto_goTypes,
		DependencyIndexes: file_apollo_proto_messages_v1_messages_proto_depIdxs,
		MessageInfos:      file_apollo_proto_messages_v1_messages_proto_msgTypes,
	}.Build()
	File_apollo_proto_messages_v1_messages_proto = out.File
	file_apollo_proto_messages_v1_messages_proto_rawDesc = nil
	file_apollo_proto_messages_v1_messages_proto_goTypes = nil
	file_apollo_proto_messages_v1_messages_proto_depIdxs = nil
}
