FROM debian:11-slim

RUN apt update && apt install --no-install-recommends -y \
  systemd \
  systemd-sysv

COPY prepare-rootfs.sh prepare-rootfs.sh
RUN chmod +x prepare-rootfs.sh

#COPY agent.sh /bin/agent.sh
#RUN chmod +x /bin/agent.sh

ENTRYPOINT ["/usr/bin/tini-static", "--", "/bin/agent.sh"]