// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: apollo/proto/worker/v1/worker.proto

package workerpb

import (
	v1 "github.com/dennishilgert/apollo/pkg/proto/shared/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KernelSpecs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *KernelSpecs) Reset() {
	*x = KernelSpecs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apollo_proto_worker_v1_worker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KernelSpecs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KernelSpecs) ProtoMessage() {}

func (x *KernelSpecs) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_proto_worker_v1_worker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KernelSpecs.ProtoReflect.Descriptor instead.
func (*KernelSpecs) Descriptor() ([]byte, []int) {
	return file_apollo_proto_worker_v1_worker_proto_rawDescGZIP(), []int{0}
}

func (x *KernelSpecs) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KernelSpecs) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type RuntimeSpecs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *RuntimeSpecs) Reset() {
	*x = RuntimeSpecs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apollo_proto_worker_v1_worker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuntimeSpecs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeSpecs) ProtoMessage() {}

func (x *RuntimeSpecs) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_proto_worker_v1_worker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeSpecs.ProtoReflect.Descriptor instead.
func (*RuntimeSpecs) Descriptor() ([]byte, []int) {
	return file_apollo_proto_worker_v1_worker_proto_rawDescGZIP(), []int{1}
}

func (x *RuntimeSpecs) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RuntimeSpecs) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type InitializeFunctionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FunctionUuid string        `protobuf:"bytes,1,opt,name=function_uuid,json=functionUuid,proto3" json:"function_uuid,omitempty"`
	Kernel       *KernelSpecs  `protobuf:"bytes,2,opt,name=kernel,proto3" json:"kernel,omitempty"`
	Runtime      *RuntimeSpecs `protobuf:"bytes,3,opt,name=runtime,proto3" json:"runtime,omitempty"`
}

func (x *InitializeFunctionRequest) Reset() {
	*x = InitializeFunctionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apollo_proto_worker_v1_worker_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitializeFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeFunctionRequest) ProtoMessage() {}

func (x *InitializeFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_proto_worker_v1_worker_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeFunctionRequest.ProtoReflect.Descriptor instead.
func (*InitializeFunctionRequest) Descriptor() ([]byte, []int) {
	return file_apollo_proto_worker_v1_worker_proto_rawDescGZIP(), []int{2}
}

func (x *InitializeFunctionRequest) GetFunctionUuid() string {
	if x != nil {
		return x.FunctionUuid
	}
	return ""
}

func (x *InitializeFunctionRequest) GetKernel() *KernelSpecs {
	if x != nil {
		return x.Kernel
	}
	return nil
}

func (x *InitializeFunctionRequest) GetRuntime() *RuntimeSpecs {
	if x != nil {
		return x.Runtime
	}
	return nil
}

var File_apollo_proto_worker_v1_worker_proto protoreflect.FileDescriptor

var file_apollo_proto_worker_v1_worker_proto_rawDesc = []byte{
	0x0a, 0x23, 0x61, 0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77,
	0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x61, 0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x23, 0x61,
	0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x68, 0x61, 0x72,
	0x65, 0x64, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x3b, 0x0a, 0x0b, 0x4b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x53, 0x70, 0x65, 0x63,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22,
	0x3c, 0x0a, 0x0c, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x70, 0x65, 0x63, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0xbd, 0x01,
	0x0a, 0x19, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x46, 0x75, 0x6e, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x66,
	0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x75, 0x69, 0x64,
	0x12, 0x3b, 0x0a, 0x06, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x23, 0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x65, 0x72, 0x6e, 0x65, 0x6c,
	0x53, 0x70, 0x65, 0x63, 0x73, 0x52, 0x06, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x12, 0x3e, 0x0a,
	0x07, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24,
	0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x77, 0x6f,
	0x72, 0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x53,
	0x70, 0x65, 0x63, 0x73, 0x52, 0x07, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x32, 0x79, 0x0a,
	0x0d, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x12, 0x68,
	0x0a, 0x0a, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x12, 0x31, 0x2e, 0x61,
	0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x77, 0x6f, 0x72, 0x6b,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65,
	0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x25, 0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65, 0x6e, 0x6e, 0x69, 0x73, 0x68, 0x69, 0x6c,
	0x67, 0x65, 0x72, 0x74, 0x2f, 0x61, 0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x3b,
	0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apollo_proto_worker_v1_worker_proto_rawDescOnce sync.Once
	file_apollo_proto_worker_v1_worker_proto_rawDescData = file_apollo_proto_worker_v1_worker_proto_rawDesc
)

func file_apollo_proto_worker_v1_worker_proto_rawDescGZIP() []byte {
	file_apollo_proto_worker_v1_worker_proto_rawDescOnce.Do(func() {
		file_apollo_proto_worker_v1_worker_proto_rawDescData = protoimpl.X.CompressGZIP(file_apollo_proto_worker_v1_worker_proto_rawDescData)
	})
	return file_apollo_proto_worker_v1_worker_proto_rawDescData
}

var file_apollo_proto_worker_v1_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_apollo_proto_worker_v1_worker_proto_goTypes = []interface{}{
	(*KernelSpecs)(nil),               // 0: apollo.proto.worker.v1.KernelSpecs
	(*RuntimeSpecs)(nil),              // 1: apollo.proto.worker.v1.RuntimeSpecs
	(*InitializeFunctionRequest)(nil), // 2: apollo.proto.worker.v1.InitializeFunctionRequest
	(*v1.EmptyResponse)(nil),          // 3: apollo.proto.shared.v1.EmptyResponse
}
var file_apollo_proto_worker_v1_worker_proto_depIdxs = []int32{
	0, // 0: apollo.proto.worker.v1.InitializeFunctionRequest.kernel:type_name -> apollo.proto.worker.v1.KernelSpecs
	1, // 1: apollo.proto.worker.v1.InitializeFunctionRequest.runtime:type_name -> apollo.proto.worker.v1.RuntimeSpecs
	2, // 2: apollo.proto.worker.v1.WorkerManager.Initialize:input_type -> apollo.proto.worker.v1.InitializeFunctionRequest
	3, // 3: apollo.proto.worker.v1.WorkerManager.Initialize:output_type -> apollo.proto.shared.v1.EmptyResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_apollo_proto_worker_v1_worker_proto_init() }
func file_apollo_proto_worker_v1_worker_proto_init() {
	if File_apollo_proto_worker_v1_worker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apollo_proto_worker_v1_worker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KernelSpecs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apollo_proto_worker_v1_worker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuntimeSpecs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apollo_proto_worker_v1_worker_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitializeFunctionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apollo_proto_worker_v1_worker_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apollo_proto_worker_v1_worker_proto_goTypes,
		DependencyIndexes: file_apollo_proto_worker_v1_worker_proto_depIdxs,
		MessageInfos:      file_apollo_proto_worker_v1_worker_proto_msgTypes,
	}.Build()
	File_apollo_proto_worker_v1_worker_proto = out.File
	file_apollo_proto_worker_v1_worker_proto_rawDesc = nil
	file_apollo_proto_worker_v1_worker_proto_goTypes = nil
	file_apollo_proto_worker_v1_worker_proto_depIdxs = nil
}
